language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - flake8 --max-line-length=119
notifications:
  slack: ohcuk:6spaME3CB7f2PGrMAcklYWqp
sudo: false
