# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-03 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einstein_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payloadreceived',
            options={'verbose_name_plural': 'Payloads Received'},
        ),
    ]
