# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-06 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0033_auto_20171205_1553'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('einstein_api', '0003_monitor_monitorpatientpairing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('stop', models.DateTimeField(blank=True, null=True)),
                ('subscription_id', models.IntegerField(unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_einstein_api_pairing_subrecords', to=settings.AUTH_USER_MODEL)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einstein_api.Monitor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_einstein_api_pairing_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='monitorpatientpairing',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='monitorpatientpairing',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='monitorpatientpairing',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='monitorpatientpairing',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='MonitorPatientPairing',
        ),
    ]
