# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-13 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opal", "0034_auto_20171214_1845"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="airway",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Allergies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                (
                    "provisional",
                    models.BooleanField(
                        default=False,
                        help_text=b"True if the allergy is only suspected. Defaults to False.",
                        verbose_name=b"Suspected?",
                    ),
                ),
                ("details", models.CharField(blank=True, max_length=255)),
                (
                    "drug_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_allergies_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opal.Drug",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Patient"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_allergies_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False, "verbose_name_plural": "Allergies"},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="AnaestheticDrug",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="AnaestheticDrugType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="AnaestheticPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("Procedure_Risks", models.TextField(blank=True, null=True)),
                (
                    "Proposed_Procedure_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "Risks_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="AnaestheticTechnique",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("Title", models.TextField(blank=True, null=True)),
                ("Description", models.TextField(blank=True, null=True)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_anaesthetictechnique_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Patient"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_anaesthetictechnique_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ASA",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="CormackLehane",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Demographics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                (
                    "hospital_number",
                    models.CharField(
                        blank=True,
                        help_text=b"The unique identifier for this patient at the hospital.",
                        max_length=255,
                    ),
                ),
                (
                    "nhs_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name=b"NHS Number",
                    ),
                ),
                ("surname", models.CharField(blank=True, max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name=b"Date of Birth"
                    ),
                ),
                ("religion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "date_of_death",
                    models.DateField(
                        blank=True, null=True, verbose_name=b"Date of Death"
                    ),
                ),
                ("post_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "gp_practice_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name=b"GP Practice Code",
                    ),
                ),
                (
                    "death_indicator",
                    models.BooleanField(
                        default=False,
                        help_text=b"This field will be True if the patient is deceased.",
                    ),
                ),
                (
                    "title_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "marital_status_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "sex_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "birth_place_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "ethnicity_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "birth_place_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opal.Destination",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_demographics_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ethnicity_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opal.Ethnicity",
                    ),
                ),
                (
                    "marital_status_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opal.MaritalStatus",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Patient"
                    ),
                ),
                (
                    "sex_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opal.Gender",
                    ),
                ),
                (
                    "title_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opal.Title",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_demographics_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False, "verbose_name_plural": "Demographics"},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Dentition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                (
                    "provisional",
                    models.BooleanField(
                        default=False,
                        help_text=b"True if the diagnosis is provisional. Defaults to False",
                        verbose_name=b"Provisional?",
                    ),
                ),
                ("details", models.CharField(blank=True, max_length=255)),
                ("date_of_diagnosis", models.DateField(blank=True, null=True)),
                (
                    "condition_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "condition_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opal.Condition",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_diagnosis_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Episode"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_diagnosis_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False, "verbose_name_plural": "Diagnoses"},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="FrailtyScale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Gases",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("inspired_carbon_dioxide", models.FloatField(blank=True, null=True)),
                ("expired_carbon_dioxide", models.FloatField(blank=True, null=True)),
                ("inspired_oxygen", models.FloatField(blank=True, null=True)),
                ("expired_oxygen", models.FloatField(blank=True, null=True)),
                ("expired_aa", models.FloatField(blank=True, null=True)),
                ("datetime", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_gases_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Patient"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_gases_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="GivenDrug",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("dose", models.CharField(max_length=255)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "drug_type_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "drug_name_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_givendrug_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug_name_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.AnaestheticDrug",
                    ),
                ),
                (
                    "drug_type_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.AnaestheticDrugType",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Patient"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_givendrug_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Induction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("Size", models.FloatField(blank=True, null=True)),
                ("Description", models.TextField(blank=True, null=True)),
                (
                    "Propofol_dose",
                    models.FloatField(blank=True, default=b"200", null=True),
                ),
                ("Atracurium_dose", models.FloatField(blank=True, null=True)),
                (
                    "Fentanyl_dose",
                    models.FloatField(blank=True, default=b"100", null=True),
                ),
                (
                    "MaskVent_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "Induction_type_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "Airway_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "Position_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "CormackLehane_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "Airway_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.airway",
                    ),
                ),
                (
                    "CormackLehane_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.CormackLehane",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Induction_type",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Investigation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("test", models.CharField(max_length=255)),
                ("date_ordered", models.DateField(blank=True, null=True)),
                ("details", models.CharField(blank=True, max_length=255)),
                ("microscopy", models.CharField(blank=True, max_length=255)),
                ("organism", models.CharField(blank=True, max_length=255)),
                ("sensitive_antibiotics", models.CharField(blank=True, max_length=255)),
                ("resistant_antibiotics", models.CharField(blank=True, max_length=255)),
                ("result", models.CharField(blank=True, max_length=255)),
                ("igm", models.CharField(blank=True, max_length=20)),
                ("igg", models.CharField(blank=True, max_length=20)),
                ("vca_igm", models.CharField(blank=True, max_length=20)),
                ("vca_igg", models.CharField(blank=True, max_length=20)),
                ("ebna_igg", models.CharField(blank=True, max_length=20)),
                ("hbsag", models.CharField(blank=True, max_length=20)),
                ("anti_hbs", models.CharField(blank=True, max_length=20)),
                ("anti_hbcore_igm", models.CharField(blank=True, max_length=20)),
                ("anti_hbcore_igg", models.CharField(blank=True, max_length=20)),
                ("rpr", models.CharField(blank=True, max_length=20)),
                ("tppa", models.CharField(blank=True, max_length=20)),
                ("viral_load", models.CharField(blank=True, max_length=20)),
                ("parasitaemia", models.CharField(blank=True, max_length=20)),
                ("hsv", models.CharField(blank=True, max_length=20)),
                ("vzv", models.CharField(blank=True, max_length=20)),
                ("syphilis", models.CharField(blank=True, max_length=20)),
                ("c_difficile_antigen", models.CharField(blank=True, max_length=20)),
                ("c_difficile_toxin", models.CharField(blank=True, max_length=20)),
                ("species", models.CharField(blank=True, max_length=20)),
                ("hsv_1", models.CharField(blank=True, max_length=20)),
                ("hsv_2", models.CharField(blank=True, max_length=20)),
                ("enterovirus", models.CharField(blank=True, max_length=20)),
                ("cmv", models.CharField(blank=True, max_length=20)),
                ("ebv", models.CharField(blank=True, max_length=20)),
                ("influenza_a", models.CharField(blank=True, max_length=20)),
                ("influenza_b", models.CharField(blank=True, max_length=20)),
                ("parainfluenza", models.CharField(blank=True, max_length=20)),
                ("metapneumovirus", models.CharField(blank=True, max_length=20)),
                ("rsv", models.CharField(blank=True, max_length=20)),
                ("adenovirus", models.CharField(blank=True, max_length=20)),
                ("norovirus", models.CharField(blank=True, max_length=20)),
                ("rotavirus", models.CharField(blank=True, max_length=20)),
                ("giardia", models.CharField(blank=True, max_length=20)),
                ("entamoeba_histolytica", models.CharField(blank=True, max_length=20)),
                ("cryptosporidium", models.CharField(blank=True, max_length=20)),
                (
                    "rhinovirus",
                    models.CharField(
                        blank=True,
                        choices=[
                            (b"pending", b"pending"),
                            (b"positive", b"positive"),
                            (b"negative", b"negative"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_investigation_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Episode"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_investigation_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("hospital", models.CharField(blank=True, max_length=255)),
                ("ward", models.CharField(blank=True, max_length=255)),
                ("bed", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_location_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Episode"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_location_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Malampati",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="MaskVent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("bp_systolic", models.FloatField(blank=True, null=True)),
                ("bp_diastolic", models.FloatField(blank=True, null=True)),
                ("pulse", models.FloatField(blank=True, null=True)),
                ("resp_rate", models.FloatField(blank=True, null=True)),
                ("sp02", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("datetime", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_observation_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Patient"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_observation_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PastMedicalHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("year", models.CharField(blank=True, max_length=4)),
                ("details", models.CharField(blank=True, max_length=255)),
                (
                    "condition_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "condition_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opal.Condition",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_pastmedicalhistory_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Episode"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_pastmedicalhistory_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name_plural": "Past medical histories",
            },
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PatientPhysicalAttributes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("height", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_patientphysicalattributes_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Patient"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_patientphysicalattributes_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="PreOpBloods",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("Hb", models.FloatField(blank=True, null=True)),
                ("Plt", models.FloatField(blank=True, null=True)),
                ("WBC", models.FloatField(blank=True, null=True)),
                ("INR", models.FloatField(blank=True, null=True)),
                ("CRP", models.FloatField(blank=True, null=True)),
                ("Urea", models.FloatField(blank=True, null=True)),
                ("Creat", models.FloatField(blank=True, null=True)),
                ("Na", models.FloatField(blank=True, null=True)),
                ("K", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_preopbloods_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Episode"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_preopbloods_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PreOpVisit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("Assessment", models.TextField(blank=True, null=True)),
                ("General_Risks", models.TextField(blank=True, null=True)),
                ("AdditionalRisks", models.TextField(blank=True, null=True)),
                ("TimeSeen", models.DateTimeField(blank=True, null=True)),
                (
                    "previous_anaesthetics_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "ASA_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "Frailty_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "Malampati_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "Dentition_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "ASA_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.ASA",
                    ),
                ),
                (
                    "Dentition_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.Dentition",
                    ),
                ),
                (
                    "Frailty_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.FrailtyScale",
                    ),
                ),
                (
                    "Malampati_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.Malampati",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_preopvisit_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Episode"
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PreviousAnaesthetics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="ProposedProcedure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Risks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("dose", models.CharField(blank=True, max_length=255)),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text=b"The date on which the patient began receiving this treatment.",
                        null=True,
                    ),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "route_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "drug_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "frequency_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_treatment_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opal.Drug",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Episode"
                    ),
                ),
                (
                    "frequency_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opal.Drugfreq",
                    ),
                ),
                (
                    "route_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opal.Drugroute",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_treatment_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Ventilators",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("mode", models.CharField(max_length=255)),
                ("peak_airway_pressure", models.FloatField(blank=True, null=True)),
                ("peep_airway_pressure", models.FloatField(blank=True, null=True)),
                ("tidal_volume", models.FloatField(blank=True, null=True)),
                ("rate", models.IntegerField(blank=True, null=True)),
                ("datetime", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_ventilators_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Patient"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_ventilators_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="preopvisit",
            name="previous_anaesthetics_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somno.PreviousAnaesthetics",
            ),
        ),
        migrations.AddField(
            model_name="preopvisit",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_somno_preopvisit_subrecords",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="induction",
            name="Induction_type_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somno.Induction_type",
            ),
        ),
        migrations.AddField(
            model_name="induction",
            name="MaskVent_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somno.MaskVent",
            ),
        ),
        migrations.AddField(
            model_name="induction",
            name="Position_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somno.Position",
            ),
        ),
        migrations.AddField(
            model_name="induction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_somno_induction_subrecords",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="induction",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="opal.Episode"
            ),
        ),
        migrations.AddField(
            model_name="induction",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_somno_induction_subrecords",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="anaestheticplan",
            name="Proposed_Procedure_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somno.ProposedProcedure",
            ),
        ),
        migrations.AddField(
            model_name="anaestheticplan",
            name="Risks_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somno.Risks",
            ),
        ),
        migrations.AddField(
            model_name="anaestheticplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_somno_anaestheticplan_subrecords",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="anaestheticplan",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="opal.Episode"
            ),
        ),
        migrations.AddField(
            model_name="anaestheticplan",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_somno_anaestheticplan_subrecords",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
