# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-24 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opal", "0034_auto_20171214_1845"),
        ("somno", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("Title", models.TextField(blank=True, null=True)),
                ("Description", models.TextField(blank=True, null=True)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_event_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Patient"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_event_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.RemoveField(model_name="anaesthetictechnique", name="created_by"),
        migrations.RemoveField(model_name="anaesthetictechnique", name="patient"),
        migrations.RemoveField(model_name="anaesthetictechnique", name="updated_by"),
        migrations.AlterField(
            model_name="induction",
            name="Fentanyl_dose",
            field=models.FloatField(blank=True, default="100", null=True),
        ),
        migrations.AlterField(
            model_name="induction",
            name="Propofol_dose",
            field=models.FloatField(blank=True, default="200", null=True),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="rhinovirus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "pending"),
                    ("positive", "positive"),
                    ("negative", "negative"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(name="AnaestheticTechnique"),
    ]
