# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-24 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opal", "0034_auto_20171214_1845"),
        ("somno", "0002_auto_20180724_1045"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnaestheticAssesment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("Assessment", models.TextField(blank=True, null=True)),
                ("General_Risks", models.TextField(blank=True, null=True)),
                ("AdditionalRisks", models.TextField(blank=True, null=True)),
                ("TimeSeen", models.DateTimeField(blank=True, null=True)),
                (
                    "Malampati_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "Dentition_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "ASA_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "Frailty_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "previous_anaesthetics_ft",
                    models.CharField(
                        blank=True, default=b"", max_length=255, null=True
                    ),
                ),
                (
                    "ASA_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.ASA",
                    ),
                ),
                (
                    "Dentition_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.Dentition",
                    ),
                ),
                (
                    "Frailty_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.FrailtyScale",
                    ),
                ),
                (
                    "Malampati_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.Malampati",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_anaestheticassesment_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Episode"
                    ),
                ),
                (
                    "previous_anaesthetics_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="somno.PreviousAnaesthetics",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_anaestheticassesment_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Bloods",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("Hb", models.FloatField(blank=True, null=True)),
                ("Plt", models.FloatField(blank=True, null=True)),
                ("WBC", models.FloatField(blank=True, null=True)),
                ("INR", models.FloatField(blank=True, null=True)),
                ("CRP", models.FloatField(blank=True, null=True)),
                ("Urea", models.FloatField(blank=True, null=True)),
                ("Creat", models.FloatField(blank=True, null=True)),
                ("Na", models.FloatField(blank=True, null=True)),
                ("K", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_bloods_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Episode"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_bloods_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Ventilation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("mode", models.CharField(max_length=255)),
                ("peak_airway_pressure", models.FloatField(blank=True, null=True)),
                ("peep_airway_pressure", models.FloatField(blank=True, null=True)),
                ("tidal_volume", models.FloatField(blank=True, null=True)),
                ("rate", models.IntegerField(blank=True, null=True)),
                ("datetime", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_ventilation_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Patient"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_ventilation_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.RemoveField(model_name="preopbloods", name="created_by"),
        migrations.RemoveField(model_name="preopbloods", name="episode"),
        migrations.RemoveField(model_name="preopbloods", name="updated_by"),
        migrations.RemoveField(model_name="preopvisit", name="ASA_fk"),
        migrations.RemoveField(model_name="preopvisit", name="Dentition_fk"),
        migrations.RemoveField(model_name="preopvisit", name="Frailty_fk"),
        migrations.RemoveField(model_name="preopvisit", name="Malampati_fk"),
        migrations.RemoveField(model_name="preopvisit", name="created_by"),
        migrations.RemoveField(model_name="preopvisit", name="episode"),
        migrations.RemoveField(
            model_name="preopvisit", name="previous_anaesthetics_fk"
        ),
        migrations.RemoveField(model_name="preopvisit", name="updated_by"),
        migrations.RemoveField(model_name="ventilators", name="created_by"),
        migrations.RemoveField(model_name="ventilators", name="patient"),
        migrations.RemoveField(model_name="ventilators", name="updated_by"),
        migrations.AlterModelOptions(
            name="givendrug", options={"verbose_name": "Drug"}
        ),
        migrations.DeleteModel(name="PreOpBloods"),
        migrations.DeleteModel(name="PreOpVisit"),
        migrations.DeleteModel(name="Ventilators"),
    ]
