# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-03 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opal", "0034_auto_20171214_1845"),
        ("somno", "0009_auto_20180731_0506"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("Medications", models.TextField(blank=True, null=True)),
                ("Allergies", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_somno_drughistory_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opal.Episode"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_somno_drughistory_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        ),
        migrations.RemoveField(model_name="drughistroy", name="created_by"),
        migrations.RemoveField(model_name="drughistroy", name="episode"),
        migrations.RemoveField(model_name="drughistroy", name="updated_by"),
        migrations.DeleteModel(name="DrugHistroy"),
    ]
