# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-02 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('somno', '0010_auto_20180802_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpatientpairing',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
