# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-03 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("somno", "0012_remove_monitorpatientpairing_user")]

    operations = [
        migrations.RemoveField(model_name="monitorpatientpairing", name="created_by"),
        migrations.RemoveField(model_name="monitorpatientpairing", name="monitor"),
        migrations.RemoveField(model_name="monitorpatientpairing", name="patient"),
        migrations.RemoveField(model_name="monitorpatientpairing", name="updated_by"),
        migrations.DeleteModel(name="Monitor"),
        migrations.DeleteModel(name="MonitorPatientPairing"),
    ]
