# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-31 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somno', '0016_auto_20180831_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='infusion',
            name='units',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
