# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somno', '0017_infusion_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anaestheticnote',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='anaestheticnote',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='infusion',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start'),
        ),
    ]
