# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-31 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("somno", "0019_auto_20180831_1109")]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.RemoveField(model_name="anaestheticnote", name="name"),
        migrations.AddField(
            model_name="anaestheticnote",
            name="name_ft",
            field=models.CharField(blank=True, default=b"", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="anaestheticnote",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Time"),
        ),
        migrations.AddField(
            model_name="anaestheticnote",
            name="name_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somno.EventType",
            ),
        ),
    ]
