# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-31 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somno', '0020_auto_20180831_1115'),
        ('somno', '0009_auto_20180731_0506'),
    ]

    operations = [
    ]
