# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-31 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("somno", "0010_auto_20180803_1057"),
        ("somno", "0021_merge_20180831_1211"),
    ]

    operations = []
