# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-28 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somno', '0023_fluids_givenfluids'),
        ('somno', '0024_auto_20180928_1034'),
    ]

    operations = [
    ]
