# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-28 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("somno", "0025_merge_20180928_1045")]

    operations = [
        migrations.RemoveField(model_name="anaestheticassesment", name="frailty_fk"),
        migrations.RemoveField(model_name="anaestheticassesment", name="frailty_ft"),
    ]
