# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-28 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somno', '0026_auto_20180928_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrailtyScale',
        ),
    ]
