# Generated by Django 2.0.13 on 2020-09-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somno', '0029_auto_20180928_1557'),
        ('somno', '0029_auto_20190314_1352'),
    ]

    operations = [
    ]
