# Generated by Django 2.0.13 on 2020-09-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somno', '0030_merge_20200903_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodysite',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bodysite',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bodysite',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceduredevice',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceduredevice',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceduredevice',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='procedurename',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='procedurename',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='procedurename',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceduresterility',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceduresterility',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceduresterility',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceduretechnique',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceduretechnique',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceduretechnique',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceduretype',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceduretype',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceduretype',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='procedureultrasound',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='procedureultrasound',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='procedureultrasound',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anaestheticprocedure',
            name='Body_Site_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anaestheticprocedure',
            name='Device_Used_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anaestheticprocedure',
            name='Drug_Used_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anaestheticprocedure',
            name='Procedure_Name_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anaestheticprocedure',
            name='Procedure_Type_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anaestheticprocedure',
            name='Sterility_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anaestheticprocedure',
            name='Technique_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anaestheticprocedure',
            name='Ultrasound_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bodysite',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='proceduredevice',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='procedurename',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='proceduresterility',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='proceduretechnique',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='proceduretype',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='procedureultrasound',
            unique_together={('code', 'system')},
        ),
    ]
