# Generated by Django 2.0.13 on 2020-09-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somno', '0031_auto_20200903_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anaestheticplan',
            name='Proposed_Procedure_fk',
        ),
        migrations.RemoveField(
            model_name='anaestheticplan',
            name='Proposed_Procedure_ft',
        ),
        migrations.AddField(
            model_name='anaestheticplan',
            name='Proposed_Procedure',
            field=models.ManyToManyField(blank=True, null=True, related_name='ProposedProcedure', to='somno.ProposedProcedure'),
        ),
    ]
