# Generated by Django 2.0.13 on 2020-09-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somno', '0032_auto_20200903_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaestheticassesment',
            name='seen_by_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='somno.Anaesthetist'),
        ),
        migrations.AddField(
            model_name='anaestheticassesment',
            name='seen_by_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
