# Generated by Django 2.0.13 on 2020-09-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somno', '0033_auto_20200903_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='givendrug',
            options={},
        ),
        migrations.AlterModelOptions(
            name='givenfluids',
            options={},
        ),
    ]
